enum Modul {
  ARTICLE = 'Artikel',
  CATEGORY = 'Kategori',
  EMPLOYMENT = 'Jabatan',
  VILLAGE_OFFICIALS = 'Perangkat Desa',
  VILLAGE_POTENTIALS = 'Potensi Desa',
  HAMLET = 'Dusun',
  LEGAL_PRODUCTS = 'Produk Hukum',
  VISI_MISI = 'Visi Misi',
  VILLAGE_INSTITUTION = 'Lembaga Desa',
  RESIDENTIAL = 'Kependudukan',
  FAMILY = 'Keluaga',
  FAMILY_DETAIL = 'Detail Keluarga',
  INSTITUTION_MEMBER = 'Anggota Lembaga',
  APBD_REPORT = 'Laporan APBDes',
  APBD_ITEM = 'Item APBDes',
  PUBLIC_ASSISTANCE = 'Bantuan',
  BENEFICIARY = 'Peserta Bantuan',
  LETTER_TYPE = 'Jenis Surat',
  LETTER_ATTRIBUTE = 'Atribut Surat',
  LETTER_TEMPLATE = 'Template Surat',
  LETTER_SUBMIT = 'Permohonan Surat',
  SUBMIT_LETTER = 'Perrmohonan Surat',
  PROSPECTIVE_VOTER = 'Calon Pemilih',
  MAP = 'Pemetaan',
  USERS = 'Pengguna',
  COMUNITY = 'Masyarakat',
  VILLAGE_ENTERPRISE = 'Lapak BUMDes',
  CITIZEN_REPORT = 'Layanan Pengaduan Masyarakat'
}

export default Modul;
