name: CI/CD Pipeline for React Frontend Dev

on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build React App
        run: npm run build --verbose  # Tambahkan --verbose untuk debugging

      - name: Debug Build Output
        run: ls -la build/ || echo "Build folder not found"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist/
          retention-days: 1

      - name: Debug Artifact Upload
        run: echo "Artifact uploaded successfully" || echo "Artifact upload failed"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: dist/

      - name: Debug Downloaded Artifact
        run: ls -la dist/ || echo "Downloaded artifact folder not found"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 2223 govillage.id >> ~/.ssh/known_hosts

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          ssh -p 2223 govz9813@govillage.id << 'EOF'
            if [ ! -d "/home/govz9813/public_html/staging/example.govillage.id" ]; then
              mkdir -p /home/govz9813/public_html/staging/example.govillage.id
            fi
            rm -rf /home/govz9813/public_html/staging/example.govillage.id/*
            exit
          EOF
          scp -r -P 2223 dist/* govz9813@govillage.id:/home/govz9813/public_html/staging/example.govillage.id/

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -p 2223 govz9813@govillage.id << 'EOF'
            if [ ! -d "/home/govz9813/public_html/production/example.govillage.id" ]; then
              mkdir -p /home/govz9813/public_html/production/example.govillage.id
            fi
            rm -rf /home/govz9813/public_html/production/example.govillage.id/*
            exit
          EOF
          scp -r -P 2223 dist/* govz9813@govillage.id:/home/govz9813/public_html/production/example.govillage.id/